<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Learning.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Email\" />
    <Folder Include="Classes\AddClass\" />
    <Folder Include="Classes\GetAllClass\" />
    <Folder Include="Classes\DeleteClass\" />
    <Folder Include="Classes\GetClassById\" />
    <Folder Include="Classes\UpdateClass\" />
    <Folder Include="StudentSubscriptions\" />
    <Folder Include="Sections\" />
    <Folder Include="Courses\" />
    <Folder Include="ExamExplanations\" />
    <Folder Include="ExamVideos\" />
    <Folder Include="Invtensives\" />
    <Folder Include="InvtensivesVideos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Learning.Domin\E-Learning.Domain.csproj" />
  </ItemGroup>

</Project>
