<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Learning.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExamExplanations\Commands\" />
    <Folder Include="ExamExplanations\Queries\" />
    <Folder Include="ExamVideos\Commands\" />
    <Folder Include="ExamVideos\Queries\" />
    <Folder Include="InvtensivesVideos\Commands\" />
    <Folder Include="InvtensivesVideos\Queries\" />
    <Folder Include="Invtensives\Commands\" />
    <Folder Include="Invtensives\Queries\" />
    <Folder Include="Lessons\Commands\AddLesson\" />
    <Folder Include="Lessons\Commands\DeleteLesson\" />
    <Folder Include="Lessons\Commands\UpdateLesson\" />
    <Folder Include="Lessons\Events\" />
    <Folder Include="Lessons\Queries\" />
    <Folder Include="StudentSubscriptions\Commands\" />
    <Folder Include="StudentSubscriptions\Events\" />
    <Folder Include="StudentSubscriptions\Queries\" />
    <Folder Include="Units\Events\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Learning.Domin\E-Learning.Domain.csproj" />
  </ItemGroup>

</Project>
